window.LAW={bar:[],courts:[]};
window.BAR_LABELS=[
{en:"Timeline",tw:"Nhyehyɛe",ewe:"Mɔ ɖoɖo",ga:"Mɔ ɖoɖo"},
{en:"Getting In",tw:"Wɔbɛhyɛ So",ewe:"Gɔmesɔsɔ",ga:"Ba"},
{en:"What You Study",tw:"Nea Wosua",ewe:"Nusi nèdrɔ̃",ga:"Sane"},
{en:"Types of Law",tw:"Mmara Ahodoɔ",ewe:"Sewo ƒe hɛnsɛsɛ",ga:"Kɛ ahodoɔ"},
{en:"The Courts",tw:"Asɛnnibea",ewe:"ŋkɔwo",ga:"Kwe"},
{en:"After the Bar",tw:"Bar Akyi",ewe:"Bar megbe",ga:"Bar kɛjɛ"},
{en:"What To Put In Mind",tw:"Deɛ Ɛsɛ Sɛ Wususu",ewe:"Nusi nèkpɔ",ga:"Kpɔ mi"}];
LAW.bar=[
{id:"timeline",emoji:"🗺️",t:{en:"Your Timeline: SHS to the Bar",tw:"W'Adwuma Nkyerɛwee",ewe:"Wò mɔ ɖoɖo",ga:"Wɔ mɔ ɖoɖo"},
steps:[
{t:"WASSCE at SHS",s:"Aim for strong passes: credit (A1–C6) in Core English, Core Maths, Integrated Science, Social Studies, plus three elective subjects."},
{t:"University LLB (4 years)",s:"Apply to an accredited law faculty. Aggregates vary by university — check each one's admission page. Degree holders may also take LLB routes."},
{t:"Pre-Bar / LPT (1 year)",s:"NEW under Act 1170 (2026): 1-year Law Practice Training at any accredited institution — universities can now apply to run it too (accreditation opens Oct 2026, full rollout 2027–28). Transitional Pre-Bar courses run for 2026 graduates and the backlog."},
{t:"National Bar Examinations",s:"The old Ghana School of Law entrance exam (IEC) is abolished. Pass the national bar exams."},
{t:"Called to the Bar",s:"The General Legal Council calls successful candidates to the Ghana Bar — ceremonies are held in October."},
{t:"Practise",s:"Join a law firm or chambers, start your own practice, or go in-house, public service or the bench."}]},
{id:"entry",emoji:"🚪",t:{en:"Getting Into Law School",tw:"Kwan A Wubɛfa Fa Mmara Nsua",ewe:"Gɔmesɔsɔ",ga:"Ba"},
items:[
{t:"With WASSCE",s:"Credit passes (A1–C6) in Core English, Core Mathematics, Integrated Science, Social Studies + three electives. Universities use aggregates — competitive programmes want a strong aggregate, so aim high in English and electives."},
{t:"With a first degree",s:"Many faculties admit degree holders into LLB programmes — a second route if you did not go straight from SHS."},
{t:"Foreign-trained",s:"Ghanaian LLB holders from common-law jurisdictions can now qualify for Ghanaian professional training under the 2026 reforms."},
{t:"Where to apply",s:"University of Ghana · KNUST · GIMPA · UPSA · UCC · University of Ghana (Legon) law faculties and accredited private universities (e.g. Central, Wisconsin, Lancaster). Always confirm accreditation with GTEC/GLC before paying fees."}]},
{id:"study",emoji:"📖",t:{en:"What You Will Study",tw:"Nea Wosua",ewe:"Nusi nèdrɔ̃",ga:"Sane"},
items:[
{t:"LLB (academic)",s:"Constitutional Law · Law of Contract · Criminal Law · Law of Torts · Land Law · Equity & Trusts · Commercial Law · Family Law · Legal Method & Interpretation · Jurisprudence · electives like Oil & Gas Law, Human Rights Law, IP."},
{t:"Law Practice Training (professional)",s:"Civil Procedure · Criminal Procedure · Law of Evidence · Conveyancing & Drafting · Advocacy & Legal Ethics · Law Practice Management · Legal Accounting."},
{t:"Former PLC subjects (for reference)",s:"The old Ghana School of Law Professional Law Course covered: ADR, Civil & Criminal Procedure, Company & Commercial Practice, Evidence, Law Practice Management & Legal Accountancy, Advocacy & Legal Ethics, Conveyancing & Drafting, Family Law & Practice, Interpretation of Deeds & Statutes."}]},
{id:"types",emoji:"🧭",t:{en:"Types of Law You Can Practise",tw:"Mmara Ahodoɔ A Wubɛtumi Adi Dwuma",ewe:"Sewo ƒe hɛnsɛsɛwo",ga:"Kɛ ahodoɔ"},
items:[
{t:"Criminal Law",s:"Prosecute or defend people in court — criminal procedure, bail, trials, appeals."},
{t:"Civil Litigation",s:"Sue or defend in disputes: contracts, negligence, defamation, debt recovery."},
{t:"Corporate & Commercial",s:"Advise companies: contracts, compliance, mergers, capital markets, banking."},
{t:"Family Law",s:"Divorce, custody, maintenance, inheritance and estate matters."},
{t:"Land & Property Law",s:"Land title litigation, conveyancing, mortgage and tenancy matters."},
{t:"Labour & Employment",s:"Fair dismissal, pensions, collective bargaining, workplace disputes."},
{t:"Constitutional & Human Rights",s:"Public interest litigation, fundamental rights enforcement, policy advocacy."},
{t:"Oil, Gas & Mining",s:"Ghana's extractive sector — petroleum agreements, mining leases, community rights."},
{t:"Tax Law",s:"Advising on GRA compliance, disputes and corporate structuring."},
{t:"Maritime & International Trade",s:"Shipping, ports, trade finance and cross-border transactions."},
{t:"Intellectual Property",s:"Trademarks, copyright, patents — protecting Ghana's creatives."},
{t:"Academia & Legal Tech",s:"Teaching, research, legal publishing and building legal-tech tools."}]},
{id:"after",emoji:"💼",t:{en:"After the Call to the Bar",tw:"Bere A Wɔfrɛ Wo Akyi",ewe:"Bar megbe",ga:"Bar kɛjɛ"},
items:[
{t:"Join a law firm or chambers",s:"Most new lawyers join established firms to learn practice, build networks and earn before branching out."},
{t:"Start your own practice",s:"After experience, open a chambers — register with the General Legal Council and get a practising certificate."},
{t:"In-house counsel",s:"Work inside banks, telcos, mining and oil companies as their lawyer."},
{t:"Public service",s:"Attorney-General's Department, state agencies, prosecutors, Registrar-General, public boards."},
{t:"The bench",s:"Become a magistrate or judge — High Court judges need 10 years' practice, Court of Appeal 12, Supreme Court 15."},
{t:"Academia & NGO work",s:"Teach law, research, or drive human-rights and policy change."}]},
{id:"mindset",emoji:"🧠",t:{en:"What To Put In Mind",tw:"Deɛ Ɛsɛ Sɛ Wususu",ewe:"Nusi nèkpɔ",ga:"Kpɔ mi"},
items:[
{t:"Grades matter — effort matters more",s:"Law is competitive. Strong English, discipline and consistency beat shortcuts."},
{t:"Costs & funding",s:"University and professional training cost real money — explore scholarships (e.g. GETFund, faculty bursaries) and plan early."},
{t:"The rules changed in 2026",s:"Act 1170 abolished the entrance exam and lets more institutions train lawyers — the backlog of thousands of LLB graduates is being cleared. Check official GLC/CLET announcements each year."},
{t:"Reading is the job",s:"Lawyers live in texts: cases, statutes, rules. Build the habit in SHS already."},
{t:"Moots & internships",s:"Join mooting competitions, legal-aid clinics and internships — they teach advocacy and open doors."},
{t:"Integrity is everything",s:"The General Legal Council can discipline or strike off lawyers. Reputation is your licence."},
{t:"English & communication",s:"Precision in writing and speaking wins cases. Practise publicly — debate clubs, writing."}]},
];
LAW.courts=[
{id:"supreme",emoji:"🧎",art:"Level 1",t:{en:"Supreme Court — The Final Word",tw:"Asɛnnibea Kunini",ewe:"Supreme Court",ga:"Supreme Kwe"},
b:{en:"Final court of appeal; alone interprets the Constitution; supervises all lower courts. CJ + at least 9 justices, sitting 5+ per case. Judges: at least 15 years' practice."},
d:{en:"Constitutional interpretation, presidential election petitions, final appeals."}},
{id:"appeal",emoji:"🧎‍♂️",art:"Level 2",t:{en:"Court of Appeal",tw:"Asɛnnibea Ketewa A Ɛhyɛ Ntoso",ewe:"Court of Appeal",ga:"Appeal Kwe"},
b:{en:"Hears appeals from the High Court, Circuit Court and Regional Tribunals. Bound by its own precedents. Judges: at least 12 years' practice."},
d:{en:"Second look at a High Court or Circuit decision."}},
{id:"high",emoji:"🧎‍♀️",art:"Level 3",t:{en:"High Court — Your Rights' Guardian",tw:"Asɛnnibea Kɛseɛ",ewe:"High Court",ga:"High Kwe"},
b:{en:"Unlimited original jurisdiction in civil and criminal matters and EXCLUSIVE power to enforce fundamental human rights (Art 33). Divisions: Commercial, Land, Labour, Criminal, Human Rights, Probate, Divorce & Matrimonial, Financial. Judges: 10+ years. Hears appeals from Circuit and District courts."},
d:{en:"Serious criminal trials, big civil claims, human-rights applications."}},
{id:"circuit",emoji:"⚖️",art:"Level 4",t:{en:"Circuit Court",tw:"Circuit Asɛnnibea",ewe:"Circuit Court",ga:"Circuit Kwe"},
b:{en:"Try summarily indictable offences (e.g. basic theft, assault) and civil claims up to a set value. Appeals go to the High Court."},
d:{en:"Mid-level crimes and smaller civil disputes."}},
{id:"district",emoji:"👨‍⚖️",art:"Level 5",t:{en:"District Court (Magistrate)",tw:"District Asɛnnibea",ewe:"District Court",ga:"District Kwe"},
b:{en:"The everyday court: minor offences, preliminary investigations, small civil claims, family and juvenile matters handled alongside Juvenile Courts and Family Tribunals."},
d:{en:"First stop for most disputes and minor cases."}},
{id:"special",emoji:"🧩",art:"Special",t:{en:"Other Bodies",tw:"Akuo A Ɛyɛ Pɛ",ewe:"Ame kuwo",ga:"Kwe mɛn"},
b:{en:"Regional Tribunals (offences against the state) · Juvenile Courts & Family Tribunals (children & family matters) · CHRAJ (human rights & administrative justice, not a court) · Election Petition rules; plus ADR — arbitration and mediation — as an alternative to court."},
d:{en:"Some matters do not start in an ordinary court."}},
];
window.QUIZZES=[
{id:"rights",emoji:"⚖️",t:{en:"Constitutional Rights Quiz",tw:"Mmara Hokwan Nsɔhwɛ",ewe:"Hokwan ƒe asiɖe",ga:"Hokwan nsɔhwɛ"},
qs:[
{q:"How soon must an arrested person be brought before court?",o:["48 hours","7 days","2 weeks","30 days"],a:0,x:"Article 14(3): within 48 hours or release."},
{q:"Who alone can interpret the Constitution?",o:["Parliament","The Supreme Court","The President","Any High Court"],a:1,x:"Article 2 — exclusive Supreme Court jurisdiction."},
{q:"What does 'child' mean under Article 28(5)?",o:["Under 16","Under 18","Under 21","Under 12"],a:1,x:"Anyone below 18 years."},
{q:"Which body helps you free of charge with rights complaints?",o:["Ghana Bar Association","CHRAJ","GRA","Electoral Commission"],a:1,x:"CHRAJ — Commission on Human Rights and Administrative Justice."},
{q:"Are you innocent or guilty until proven guilty?",o:["Guilty","Innocent","Depends on the case","Depends on the judge"],a:1,x:"Article 19 — presumption of innocence."},
{q:"Can non-citizens in Ghana enjoy fundamental rights?",o:["No","Only workers","Yes","Only students"],a:2,x:"Article 12(2) — every person in Ghana, whatever status."},
{q:"Which court exclusively enforces fundamental human rights?",o:["District Court","Circuit Court","High Court","Court of Appeal"],a:2,x:"Article 33(1) — High Court jurisdiction."},
{q:"Taking property without compensation is…",o:["Allowed in emergencies","Unconstitutional","Allowed for roads","Allowed for tax debts"],a:1,x:"Article 20 requires prompt and fair compensation."}]},
{id:"bar",emoji:"🎓",t:{en:"Road to the Bar Quiz",tw:"Mmaranimfo Nsɔhwɛ",ewe:"Lawyer ƒe asiɖe",ga:"Lawyer nsɔhwɛ"},
qs:[
{q:"Under the Legal Education Act 2026 (Act 1170), how many stages lead to the Bar?",o:["3","4","5","6"],a:1,x:"LLB → Law Practice Training → National Bar Exams → Call to the Bar."},
{q:"What happened to the old Ghana School of Law entrance exam?",o:["It is harder","It is abolished","It is online only","It is doubled"],a:1,x:"The IEC entrance examination was abolished by Act 1170."},
{q:"How long must a Supreme Court judge have practised law?",o:["5 years","10 years","15 years","20 years"],a:2,x:"At least 15 years for the Supreme Court."},
{q:"Who calls new lawyers to the Ghana Bar?",o:["Parliament","The Chief Justice alone","The General Legal Council","Ghana Bar Association"],a:2,x:"The GLC regulates and calls members to the Bar."},
{q:"Which court first hears most appeals from Circuit Courts?",o:["Supreme Court","High Court","Court of Appeal","District Court"],a:1,x:"High Courts hear appeals from Circuit Courts."},
{q:"How long is the new Law Practice Training (LPT)?",o:["3 months","6 months","1 year","4 years"],a:2,x:"One year of Law Practice Training under the new framework."}]},
{id:"kids",emoji:"🧒",t:{en:"Children's Rights Quiz",tw:"Mmofra Hokwan Nsɔhwɛ",ewe:"Kpɔviwo ƒe asiɖe",ga:"Ablekuma nsɔhwɛ"},
qs:[
{q:"Is basic education free and compulsory in Ghana?",o:["No","Only in cities","Yes","Only for boys"],a:2,x:"Article 25(1)(a) — free, compulsory, universal."},
{q:"Can a child be denied school because of a parent's religion?",o:["Yes","No","Only in private schools","If the parent agrees"],a:1,x:"Article 28(4) forbids it."},
{q:"At what age does 'child' protection end?",o:["12","15","18","21"],a:2,x:"Article 28(5) — below 18."},
{q:"Can children be given dangerous or education-harming work?",o:["Yes, if paid","Never","Only in holidays","If parents agree"],a:1,x:"Article 28(2) — work threatening health, education or development is barred."},
{q:"If a child is mistreated, who can you tell?",o:["Nobody","The police/Social Welfare/CHRAJ","Only friends","Only the family"],a:1,x:"Police DVVSU, Social Welfare and CHRAJ all protect children."},
{q:"Is cruel punishment of children against the Constitution?",o:["Yes","No","Sometimes","Only at school"],a:0,x:"Article 28(3) — no torture or cruel, inhuman or degrading treatment."}]},
];
window.QA=[
{kw:["police","arrest","search","house","warrant"],a:"Your home cannot be searched except as law permits (Art 18). If police want to search, ask to see a valid warrant. During a lawful arrest they may search you and your immediate surroundings."},
{kw:["arrest","detain","custody","48"],a:"On arrest they must tell you why immediately, in a language you understand, and that you may have a lawyer of your choice (Art 14(2)). You must be taken to court within 48 hours or released (Art 14(3)). See SOS for full steps."},
{kw:["lawyer","free","legal aid","cannot afford"],a:"The Legal Aid Commission gives free legal advice to qualifying persons, and CHRAJ handles rights complaints free of charge. Check the Enforcement section."},
{kw:["chraj","complaint","report","corruption","unfair"],a:"CHRAJ investigates rights violations, unfair administrative actions and corruption — free and confidential. Visit your regional or district CHRAJ office with your story and any documents."},
{kw:["bribe","bribery","pay money"],a:"You never have to pay a bribe — not to police, not to officials. It is corruption. Report it to CHRAJ or the police anti-corruption unit."},
{kw:["child","children","school","kid"],a:"Every child under 18 has constitutional protection (Art 28): free compulsory basic education (Art 25), no harmful work, no cruel punishment, and no denial of medicine or school because of beliefs. Open the Children's section."},
{kw:["land","property","compensation","house taken"],a:"Your property cannot be taken without due process and prompt, fair compensation (Art 20). Demand compensation in writing and get legal help — see Enforcement."},
{kw:["wife","husband","divorce","spouse","marriage property"],a:"Spouses have equal rights to property acquired during marriage, and fair provision on divorce or death (Art 22). Keep records of contributions."},
{kw:["job","work","salary","pay","employer","fired"],a:"You are entitled to safe, healthy conditions and equal pay for equal work, and to join a union (Art 24). Unfair treatment: complain to the Labour Department; a dismissed employee can challenge unfair termination."},
{kw:["vote","election","register"],a:"Every citizen 18+ has the right to vote and be registered (Art 42). Contact the Electoral Commission."},
{kw:["become","lawyer","law school","bar","llb","wassce"],a:"Path: WASSCE → accredited LLB → 1-year Law Practice Training (new under Act 1170, 2026) → National Bar Exams → Called to the Bar (October ceremonies). The old entrance exam is abolished. See 'Road to the Bar'."},
{kw:["court","which court","sue","tribunal"],a:"District/Magistrate: minor cases. Circuit: mid-level crime and small claims. High Court: serious matters + human-rights enforcement. Court of Appeal, then Supreme Court on appeal. See The Courts section."},
{kw:["torture","beat","hit","abuse","treated badly"],a:"No one may torture or subject you to cruel, inhuman or degrading treatment or punishment (Art 15) — including in custody. Report to CHRAJ and a lawyer immediately."},
{kw:["speech","insult","facebook","say anything","express"],a:"You have freedom of expression including freedom of the press (Art 21(1)(a)) — but it is subject to the rights of others and the public interest (defamation laws still apply)."},
{kw:["religion","church","mosque","believe"],a:"Freedom to practise any religion and manifest it (Art 21(1)(c)) — and no child may be denied school or medicine because of beliefs (Art 28(4))."},
];
