window.DB={facts:[],rights:[],enforcement:[],kids:{kids:[],adults:[]},sos:{rights:[],contacts:[]}};
window.UI={
navHome:{en:"Home",tw:"Fie",ewe:"Dzadzɛ",ga:"Tsoo"},
navRights:{en:"Rights",tw:"Hokwan",ewe:"Hokwanwo",ga:"Hokwan"},
navKids:{en:"Kids",tw:"Mmofra",ewe:"Kpɔviwo",ga:"Ablekuma"},
navBar:{en:"Bar",tw:"Bar",ewe:"Bar",ga:"Bar"},
homeTitle:{en:"Know Your Rights, Ghana! 🇬🇭",tw:"Kenken Wo Hokwan, Ghana! 🇬🇭",ewe:"Kenɛ Wò Hokwanwo, Ghana! 🇬🇭",ga:"Kenɛ Hokwanwo, Ghana! 🇬🇭"},
homeSub:{en:"The Constitution is yours. Learn it. Use it. Share it.",tw:"Mmara no yɛ wo dea. Sua no. Fa di dwuma. Kyɛ no.",ewe:"Sewoxexe ŋuti dodokpɔea enye wò. Adrɔ̃e. Atsɔe. Akpɔe ɖa.",ga:"Koni ma ye he. Sane e. Atsɛɛ e. Kɛɛ e ake."},
homeCta1:{en:"📖 Start Learning",tw:"📖 Fi ase sua",ewe:"📖 Dzi ƒe gɔme",ga:"📖 Ba sane"},
homeCta2:{en:"🚨 Emergency SOS",tw:"🚨 Mmaeɛmfeɛ SOS",ewe:"🚨 Tanyawo SOS",ga:"🚨 Kɛja SOS"},
exploreTitle:{en:"Explore",tw:"Hwehwɛ",ewe:"Di",ga:"Kane"},
rightsTitle:{en:"⚖️ Your Fundamental Rights",tw:"⚖️ Wo Kɛseɛ Hokwan",ewe:"⚖️ Wò Gɔmedzedze Hokwanwo",ga:"⚖️ Hokwan Kuuwo"},
rightsSub:{en:"Chapter 5 of Ghana's 1992 Constitution — Articles 12 to 33.",tw:"Ghana Mmara a ɛfiri 1992, Faeka 5 — Nkyekyɛmu 12 kosi 33.",ewe:"Ghana ƒe sewo 1992 ƒe katã 5 — Article 12 ɖo 33.",ga:"Ghana koni 1992, Falal 5 — 12 dzu 33."},
kidsTitle:{en:"🧒 Children's Rights",tw:"🧒 Mmofra Hokwan",ewe:"🧒 Kpɔviwo ƒe Hokwanwo",ga:"🧒 Ablekuma Hokwanwo"},
kidsSub:{en:"Article 28 of the Constitution protects every child under 18.",tw:"Ahyɛde 28 di ban mmofra a wɔadi mfeɛ duonu.",ewe:"Article 28 ƒe sewo kpɔa kpɔvi si wo xɔ ƒe 18.",ga:"Article 28 la kɛɛ ablekuma ko si xɔ 18 shwi."},
enfTitle:{en:"🛡️ Enforcement & Where to Get Help",tw:"🛡️ Hokwan a Wobɛtumi De Di",ewe:"🛡️ Hokwanwo Ŋuti Dzadzenu",ga:"🛡️ Hokwan Shikɔŋŋɔ"},
enfSub:{en:"A right you cannot enforce is a right you cannot use. Here is how to act.",tw:"Hokwan a wuntumi mfa di dwuma no, wuntumi mde. Wei na wobɛfa so.",ewe:"Hokwan si màɖe nu o la, wo melia na o. Ale si nèwɔnae.",ga:"Hokwan ko shɛ noɔ shia. Nɛɛ nibɛ na eheɛ."},
courtsTitle:{en:"🏛️ The Court System",tw:"🏛️ Asɛnnibea Nhyehyɛe",ewe:"🏛️ Xexeamuwo ƒe ɖoɖo",ga:"🏛️ Kwejiamo"},
courtsSub:{en:"From the Magistrate's bench to the Supreme Court.",tw:"Firi asɛnnibea ketewa kɔsi asɛnnibea kunini.",ewe:"Tso Magistrate va ɖo Supreme Court.",ga:"Magistrate dzan dzu Supreme Kwe."},
barTitle:{en:"🎓 Road to the Bar",tw:"🎓 Kwan a Yɛbɛfa Yɛ Mmaranimfo",ewe:"🎓 Mɔ si li kpɔa lawyer",ga:"🎓 Mɔ ko ba lawyer"},
barSub:{en:"How to become a lawyer in Ghana — from SHS to the courtroom.",tw:"Sɛn na wobɛyɛ mmaranimfo wɔ Ghana — firi SHS kɔsi asɛnnibea.",ewe:"Kaka woazu lawyer le Ghana — tso SHS va xexeame.",ga:"Kɛ lawyer Ga — SHS dzan kwe."},
quizTitle:{en:"🎯 Play & Learn",tw:"🎯 Bɔ Agorɔ Sua",ewe:"🎯 Adu ƒe kple adrɔ̃",ga:"🎯 Bɔ Sane"},
quizSub:{en:"Test yourself. Learn faster. Score higher.",tw:"Pro wo ho. Sua ntɛm. Di nkɔsoɔ.",ewe:"Yesrɔ̃ wò tɔgbi. Adrɔ̃ kaba. Xɔ dzidzenu gã.",ga:"Yesɛɛ he. Sane gbɔ. Xɔ kɛje."},
askLabel:{en:"💬 Ask about your rights",tw:"💬 Bisa wo ho hokwan",ewe:"💬 Bia wò hokwanwo ŋu",ga:"💬 Bia hokwanwo"},
askBtn:{en:"Ask",tw:"Bisa",ewe:"Bia",ga:"Bia"},
searchPh:{en:"Search rights, courts, lawyers…",tw:"Hwehwɛ hokwan, asɛnnibea…",ewe:"Di hokwanwo, ŋkɔwo…",ga:"Kane hokwan, kwe…"},
sosChild:{en:"A child is in danger? Tell an adult you trust, or call the police on 112/191. You can also visit the Department of Social Welfare or CHRAJ in your district. Protecting children is everyone's duty.",tw:"Mmɔfra baasi wɔ mmaeɛmfeɛ mu? Ka kyerɛ onipa a wugye no di, anaasɛ frɛ mpanimfo 112/191. Ewopɛ sɛ wɔkasa afiri nsɛm ano a, frɛ Social Welfare anaasɛ CHRAJ wɔ wo mpɔtam hɔ.",ewe:"Kpɔvi si xɔ blibo? Gblɔ na amesi wòxɔɔ fi, alo yiɖo polisifo 112/191. Naneke Department of Social Welfare alo CHRAJ me le district la me. Kpɔviwo ƒe kpɔkpɔ nye mɔ̃ɖanuwu ƒe dɔ.",ga:"Ablekuma ko shɛ jamɔ? Gbee amɛ ko i konɛ, alo yi 112/191 polisɛ. Eya ake, ye Department of Social Welfare alo CHRAJ district me."},
install:{en:"📲 Install this app on your phone",tw:"📲 Tso app yi wɔ wo fon",ewe:"📲 Kpɔ app sia ɖe wò fɔnu dzi",ga:"📲 Kpɔ app bɛ fon me"},
helpful:{en:"Was this helpful?",tw:"Na eyi boa wo?",ewe:"Eya la kɔ ɖe wò ɖoa?",ga:"Nɛɛ bɔ heɛ?"},
};
DB.facts=[
{en:"'Child' in Ghana's Constitution means anyone below 18 years — Article 28(5)."},
{en:"You must be brought before a court within 48 hours of arrest — Article 14(3)."},
{en:"The Supreme Court alone can interpret the Constitution — Article 2."},
{en:"CHRAJ helps you free of charge if your rights are violated."},
{en:"Free, compulsory basic education is a constitutional right — Article 25(1)(a)."},
{en:"Every new lawyer is called to the Bar by the General Legal Council — bar week is in October."},
{en:"Act 1170 (2026) scrapped the old law-school entrance exam — admission is now by each accredited institution."},
{en:"The High Court alone can enforce fundamental human rights — Article 33(1)."},
{en:"Judges of the Supreme Court must have practised law for at least 15 years."},
{en:"Everyone in Ghana enjoys these rights — citizens and non-citizens alike."},
];
DB.rights=[
{id:"equality",cat:"equality",emoji:"🤝",art:"Arts 12 & 17",t:{en:"Equality & Freedom from Discrimination",tw:"Pɛpɛrɛpɛrɛ & Hokwan Kɛkɛ",ewe:"Atikɔkɔkɔ & Nyadzɔdzɔ",ga:"Atɛŋ & Hokwan"},
st:{en:"Adjoa was the best student, but they said: 'A girl cannot lead.' She knew the Constitution disagreed."},
b:{en:"Nobody may treat you differently because of your tribe, skin colour, gender, religion, political views, or where you come from. Everyone is equal before the law."},
d:{en:"If someone discriminates against you at work, school or in public life, complain to CHRAJ or go to court."}},
{id:"life",cat:"life",emoji:"❤️",art:"Art 13",t:{en:"Right to Life",tw:"Ekome Nkwa Hokwan",ewe:"Agbẽ Hokwan",ga:"Nɔŋŋ Hokwan"},
st:{en:"No one may take your life on their own authority — only a lawful court sentence can do that."},
b:{en:"Your life cannot be intentionally taken except through a proper court sentence for a crime. Deadly force is lawful only in extreme cases like self-defence, lawful arrest or stopping a riot."},
d:{en:"If someone threatens your life, report to the police immediately."}},
{id:"liberty",cat:"life",emoji:"🔓",art:"Art 14",t:{en:"Personal Liberty & Your Rights on Arrest",tw:"Wo Hokwan Ne Wokyerɛ Wo",ewe:"Wò Gɔmedzedze Ŋusẽ",ga:"Hokwan Ko Be"},
st:{en:"If the police arrest you, you do not lose your rights. The Constitution steps in immediately."},
b:{en:"You may only be detained in specific lawful situations (e.g. a court order or reasonable suspicion of a crime). If arrested you must be told WHY immediately, in a language you understand, and told you have a right to a lawyer of your choice."},
d:{en:"Ask: 'Why am I arrested?' and 'I want a lawyer.' Note the officer's name and station."}},
{id:"dignity",cat:"life",emoji:"🫱",art:"Art 15",t:{en:"Human Dignity: No Torture or Degrading Treatment",tw:"Amammerɛ: Wunni Hu Ho Bɔne",ewe:"Ame Ŋuti Gbɔgbɔ",ga:"Amɛhe"},
st:{en:"In custody, nobody may beat, torture or humiliate you. Your dignity is protected."},
b:{en:"You shall not be subjected to torture or cruel, inhuman or degrading treatment or punishment — whether or not you are arrested."},
d:{en:"If you are mistreated in custody, report it to CHRAJ and a lawyer as soon as you can."}},
{id:"slavery",cat:"life",emoji:"⛓️",art:"Art 16",t:{en:"No Slavery or Forced Labour",tw:"Nkɔsoɔ Hokwan",ewe:"Melia Adu Adzɔ Alakpa",ga:"Nɔŋŋ Adɛɛ"},
st:{en:"You cannot be owned, sold, or forced to work without pay."},
b:{en:"Slavery, servitude and forced labour are prohibited. Exception: lawful prison labour or emergency civic duties."},
d:{en:"Report forced labour or servitude to CHRAJ or the police."}},
{id:"privacy",cat:"life",emoji:"🏠",art:"Art 18",t:{en:"Privacy of Home & Property",tw:"Wo Fi Ne Nsaasoɔ Hokwan",ewe:"Wò Xexeame Ŋkeke",ga:"Ko Dzaŋŋ"},
st:{en:"Your home is your shield. Nobody may search it or take your things without lawful reason."},
b:{en:"Your home, property, correspondence and finances cannot be searched, entered, seized or interfered with except as permitted by law — e.g. with a valid search warrant or during a lawful arrest."},
d:{en:"If police want to search your home, politely ask: 'Show me the warrant.'"}},
{id:"fairtrial",cat:"life",emoji:"⚖️",art:"Art 19",t:{en:"Fair Trial & Presumption of Innocence",tw:"Atɛntɛrebɔ & Ahomasoɔ",ewe:"Sewoxexe Nyu Nyu",ga:"Kwe Kɛkɛ"},
st:{en:"You are innocent until a court proves you guilty."},
b:{en:"You are innocent until proven guilty by a competent court. You are entitled to a fair, public hearing within a reasonable time, a lawyer of your choice, and the chance to challenge evidence against you."},
d:{en:"Say nothing you do not have to, ask for a lawyer, and ask your family to find one."}},
{id:"property",cat:"work",emoji:"🏘️",art:"Art 20",t:{en:"Property Rights & Compensation",tw:"Wo Agyapadeɛ Hokwan",ewe:"Wò Dzasi Hokwan",ga:"Dza Hokwan"},
st:{en:"Nobody — not even the government — can take your property without due process and payment."},
b:{en:"Your property cannot be taken except under a court-ordered compulsory acquisition, and only with prompt and fair compensation."},
d:{en:"If your land or property is taken, demand compensation in writing and get legal help."}},
{id:"spouses",cat:"work",emoji:"💍",art:"Art 22",t:{en:"Property Rights of Spouses",tw:"Awofoɔ Hokwan",ewe:"Srɔ̃lawo ƒe Dzasi",ga:"Dzamɛ Hokwan"},
st:{en:"Marriage does not cancel your right to fair property on divorce or death."},
b:{en:"Spouses have equal rights to property acquired during marriage. On divorce or death, you are entitled to a fair share — property held jointly belongs to both."},
d:{en:"Keep records of what you own and contributed — it helps at separation."}},
{id:"work",cat:"work",emoji:"🔨",art:"Art 24",t:{en:"Work, Fair Pay & Rest",tw:"Adwuma, Sikakɔkɔ Ne Ahomeɛ",ewe:"Dɔ, Ƒe Ðoƒo & Gbagbe",ga:"Dɛɛ Kɛ"},
st:{en:"Equal pay for equal work is your right — so is rest and safe conditions."},
b:{en:"Everyone has the right to work under satisfactory, safe and healthy conditions, equal pay for equal work, rest and leisure, and to form or join a trade union."},
d:{en:"If your employer denies fair pay or safety, complain to the Labour Department or a union."}},
{id:"education",cat:"work",emoji:"📚",art:"Art 25",t:{en:"Right to Education",tw:"Nnwomapa Hokwan",ewe:"Nusrɔ̃ Hokwan",ga:"Sane Hokwan"},
st:{en:"Basic education is free, compulsory and universal — for every child."},
b:{en:"Basic education shall be free, compulsory and universal. Higher education shall be equally accessible to all on the basis of capacity."},
d:{en:"If a child is refused public basic education, complain to the Ghana Education Service or CHRAJ."}},
{id:"culture",cat:"work",emoji:"🪘",art:"Art 26",t:{en:"Culture — With Limits",tw:"Amammerɛ Ne Nneyɛeɛ Bɔne",ewe:"Agbenɔnɔ Ŋutome",ga:"Amɛ Bɔbɔ"},
st:{en:"Culture is beautiful — but practices that dehumanize people are illegal."},
b:{en:"You may enjoy your culture and language, but every customary practice which dehumanizes or is injurious to a person's physical or mental well-being is prohibited."},
d:{en:"Harmful practices — report them to police or CHRAJ, even if tradition calls them 'normal'."}},
];
DB.rights.push(
{id:"adminjustice",cat:"everyone",emoji:"📑",art:"Art 23",t:{en:"Administrative Justice",tw:"Ɔman Dwumadibea Atɛnteɛ",ewe:"Dɔwɔlawo ƒe Atsyɔ̃li",ga:"Ɔman Dɛɛ"},
st:{en:"Public officials must treat you fairly — you can challenge unfair decisions."},
b:{en:"Where an administrative body acts unfairly against you, you have the right to be given written reasons and to ask a court or a higher officer to review the action."},
d:{en:"Ask for the decision in writing, then seek help from CHRAJ or a lawyer."}},
{id:"women",cat:"everyone",emoji:"👩",art:"Art 27",t:{en:"Women's Rights",tw:"Mmaa Hokwan",ewe:"Nyɔnuwo ƒe Hokwanwo",ga:"Nyɔŋŋ Hokwan"},
st:{en:"Women deserve equal opportunity and dignity — at work, in marriage, and everywhere."},
b:{en:"Rights and protections guaranteed to women include maternity leave with pay, facilities in workplaces, and protection from practices that endanger health or dignity."},
d:{en:"Facing discrimination or harmful treatment? CHRAJ handles such complaints."}},
{id:"children",cat:"everyone",emoji:"🧒",art:"Art 28",t:{en:"Children's Rights",tw:"Mmofra Hokwan",ewe:"Kpɔviwo ƒe Hokwanwo",ga:"Ablekuma Hokwan"},
st:{en:"Every child under 18 has special protection under the Constitution."},
b:{en:"Children get special care, protection from harmful work, no cruel punishment, and equal rights whether born inside or outside marriage. See the Children's section for details."},
d:{en:"Open the Children's Rights section in the menu."}},
{id:"disabled",cat:"everyone",emoji:"♿",art:"Art 29",t:{en:"Rights of Disabled Persons",tw:"Onipa A Ɔwɔ Ho Bɔne Hokwan",ewe:"Amesiwo Gbɔ Nu Yeye",ga:"Amɛ Shɛ"},
st:{en:"Persons with disabilities must be protected from exploitation and mistreatment."},
b:{en:"Disabled persons have the right to live with family, participate in society, and be protected against all exploitation and discriminatory, abusive or degrading treatment. Public places should be accessible."},
d:{en:"If a disabled person is exploited or denied access, complain to CHRAJ."}},
{id:"sick",cat:"everyone",emoji:"🏥",art:"Art 30",t:{en:"Rights of the Sick",tw:"Yarefoɔ Hokwan",ewe:"Asixɔxɔ Kpɔla",ga:"Kɛ Kokɔɔ"},
st:{en:"Nobody may deny you treatment because of your beliefs or condition."},
b:{en:"A person unable to give consent shall not be deprived of medical treatment, education or other benefits by reason only of religious or other beliefs."},
d:{en:"Denied care? Contact CHRAJ or the health facility's administrator."}},
{id:"emergency",cat:"everyone",emoji:"🚨",art:"Arts 31 & 32",t:{en:"Your Rights in an Emergency",tw:"Wo Hokwan Wɔ Mmaeɛmfeɛ Mu",ewe:"Wò Hokwan Le Tanyawu",ga:"Hokwan Kɛja"},
st:{en:"Even during a state of emergency, your core rights do not disappear."},
b:{en:"Emergency powers are time-limited and supervised by Parliament. Anyone detained under emergency law must be told the grounds, and has the right to complain to a tribunal about their detention."},
d:{en:"Ask on what legal basis you are held, and tell your family where you are."}},
{id:"enforce33",cat:"everyone",emoji:"🏛️",art:"Art 33",t:{en:"Taking Your Rights to Court",tw:"Kɔ Asɛnnibea Fa Wo Hokwan",ewe:"Yi ŋkɔ dom",ga:"Kɔ Kwe"},
st:{en:"Rights have power because courts can enforce them — and CHRAJ helps for free."},
b:{en:"If a right is violated you may apply to the High Court or the Supreme Court for redress, or complain to CHRAJ free of charge."},
d:{en:"See the 'Enforcement & Help' section for step-by-step guidance."}},
);
DB.enforcement=[
{id:"art33",emoji:"🏛️",art:"Art 33",t:{en:"Take Your Case to Court",tw:"Kɔ Asɛnnibea",ewe:"Yi ŋkɔ dom",ga:"Kɔ Kwe"},
st:{en:"Anyone whose rights are violated can go to the High Court or Supreme Court."},
b:{en:"Article 33 lets you apply directly for redress. The High Court handles fundamental human-rights cases; constitutional questions go to the Supreme Court."},
d:{en:"Go to the High Court registry (or any court) and ask how to file a human-rights application."}},
{id:"chraj",emoji:"🛡️",art:"CHRAJ",t:{en:"CHRAJ — Free Help",tw:"CHRAJ — Mmoa A Ɛnyɛ Nsɛee",ewe:"CHRAJ — Fofo",ga:"CHRAJ"},
st:{en:"The Commission on Human Rights and Administrative Justice helps you at no cost."},
b:{en:"CHRAJ investigates rights violations, unfair administrative actions and corruption. Offices exist in every region. Complaints are free and confidential."},
d:{en:"Visit the CHRAJ office in your regional capital with your story and any papers."}},
{id:"legalaid",emoji:"🤲",art:"Legal Aid",t:{en:"Legal Aid Commission",tw:"Mmara Mmoa Dwumadibea",ewe:"Lawyer ƒe Mɔɖeɖe",ga:"Legal Bɔɔlo"},
st:{en:"Cannot afford a lawyer? Legal Aid provides free or subsidised legal services."},
b:{en:"The Legal Aid Commission gives free legal advice and representation to those who qualify, including criminal, civil and family matters."},
d:{en:"Find a Legal Aid office at the High Court complex or your district — bring ID."}},
{id:"complaint",emoji:"✍️",art:"Steps",t:{en:"How to File a Complaint",tw:"Sɛnnea Wubɛtumi Aka Asɛm",ewe:"Aleke Wòaɖo Dɔɖaŋu",ga:"Nɛɛ Bɛ Kɛ"},
st:{en:"Report violations — it works. Many cases are resolved without going to court."},
b:{en:"1) Write down what happened, when, where and who. 2) Collect documents or witnesses. 3) Take it to CHRAJ, the police (for crimes) or a court. 4) Keep a copy of everything you submit."},
d:{en:"Never pay a bribe to get help. If asked, report it."}},
{id:"police",emoji:"👮",art:"Police duties",t:{en:"What Police Must Do",tw:"Asofoɔ Deɛ Wɔbɛyɛ",ewe:"Polisifo ƒe Dɔlawo",ga:"Polisifo Bɛ"},
st:{en:"Arrest rules exist to protect everyone — including you."},
b:{en:"On arrest they must identify themselves, tell you the reason, inform you of your right to a lawyer, and take you to court within 48 hours. Searches need lawful grounds."},
d:{en:"Stay calm, obey lawful instructions, and remember — say nothing until your lawyer arrives."}},
];
DB.kids.kids=[
{id:"k1",emoji:"🏫",t:{en:"You have the right to go to school",tw:"Wunya nnwomapa hokwan",ewe:"Wò suku ƒe hokwan",ga:"Sane hokwan"},
b:{en:"Every child can go to school. Basic school is free and nobody can stop you because you are a boy or a girl."}},
{id:"k2",emoji:"❤️",t:{en:"You have the right to be cared for",tw:"Wunya hokwan sɛ wɔhɔ wo ban",ewe:"Wò hokwan nye be woakpɔ ɖe",ga:"Hokwan bɛ"},
b:{en:"Your parents and family must care for you and keep you safe."}},
{id:"k3",emoji:"🎒",t:{en:"No work that hurts you",tw:"Nsaasoɔ a ɛbɔ wo ho bɔne",ewe:"Dɔ siwo mele o",ga:"Dɛɛ bɛ"},
b:{en:"You should not be given work that hurts your body, stops your school, or is dangerous."}},
{id:"k4",emoji:"🛑",t:{en:"Nobody may hurt or punish you cruelly",tw:"Wunni tumi abɔ wo ho",ewe:"Ame aɖe melia be yeatseŋ wo o",ga:"Ko be be mi"},
b:{en:"Beating that hurts, humiliation or cruel punishment is against the law — even from adults you know."}},
{id:"k5",emoji:"💊",t:{en:"Nobody can refuse you medicine or school",tw:"Wunni tumi apegu wo ayaresa",ewe:"Ame aɖe melia be yeaxɔ asike o",ga:"Ko be bɛ mi"},
b:{en:"You cannot be denied medicine, school or help because of someone's religion or belief."}},
{id:"k6",emoji:"🗣️",t:{en:"You can speak up and be heard",tw:"Wunya hokwan sɛ wokasa",ewe:"Wòatso agbã",ga:"Kɔ he"},
b:{en:"If something is wrong, tell an adult you trust — a parent, teacher, or the police."}},
];
DB.kids.adults=[
{id:"a1",emoji:"📜",art:"Art 28",t:{en:"Article 28 — The Core Rules",tw:"Ahyɛde 28",ewe:"Article 28 — Ɖoɖo Kpɔtɔ",ga:"Art 28"},
b:{en:"Parents must undertake care, maintenance and upbringing, with the child's interest paramount (Art 28(1)(c)). Children get special protection against physical and moral hazards (Art 28(1)(d)). Children are protected from work that threatens health, education or development (Art 28(2)). No child shall be subjected to torture or cruel, inhuman or degrading treatment (Art 28(3)). No child shall be deprived of medical treatment, education or other benefits because of religious or other beliefs (Art 28(4)). 'Child' means anyone below 18 (Art 28(5))."}},
{id:"a2",emoji:"⛏️",art:"Art 28(2)",t:{en:"No Work That Threatens Health, Education or Development",tw:"Nsaasoɔ A Ɛyɛ Hu",ewe:"Dɔ Siwo Kpɔa Agbẽ",ga:"Dɛɛ Bɛ"},
b:{en:"No child shall be engaged in work that constitutes a threat to health, education or development. Under the Children's Act (Act 560): generally no full-time work below age 15 and no hazardous work below 18."},
d:{en:"Report child labour to Social Welfare or the police."}},
{id:"a3",emoji:"🚫",art:"Arts 15 & 26(2)",t:{en:"No Cruel Punishment or Harmful Practices",tw:"Amammerɛ Bɔne",ewe:"Ŋuɖuɖu ƒe Atsyɔ̃ɖoɖo",ga:"Amɛ Shɛ"},
b:{en:"No torture or cruel, inhuman or degrading treatment of children (Art 15, Art 28(3)). Customary practices that dehumanize or injure physical or mental well-being are prohibited (Art 26(2))."}},
{id:"a4",emoji:"📖",art:"Beyond the Constitution",t:{en:"Key Child-Protection Laws",tw:"Mmara A Ɛbɔ Mmofra",ewe:"Sewo ƒe ɖoɖo",ga:"Kɛ Bɔɔlo"},
b:{en:"Children's Act 1998 (Act 560) · Juvenile Justice Act 2003 (Act 653) · Domestic Violence Act 2007 (Act 732) · Human Trafficking Act 2005 (Act 694) · UN Convention on the Rights of the Child (ratified by Ghana, 1990)."}},
{id:"a5",emoji:"📞",art:"Report",t:{en:"If a Child Is in Danger",tw:"Sɛ Mmɔfra Wɔ Mmaeɛmfeɛ Mu",ewe:"Ne kpɔvi le tanyawu",ga:"Ablekuma kɛja"},
b:{en:"Contact the Domestic Violence & Victim Support Unit (DVVSU) of the Ghana Police, the Department of Social Welfare, or CHRAJ. Keep the child safe first; document everything."},
d:{en:"Find the DVVSU desk at any regional police headquarters."}},
{id:"a6",emoji:"📚",art:"Art 25",t:{en:"Education Is a Duty Too",tw:"Nnwomapa Yɛ Dɔmfoɔ",ewe:"Nusrɔ̃ nye dɔ",ga:"Sane bɛ"},
b:{en:"Basic education is free and compulsory — parents must send children to school and the state must provide it. Religious beliefs are never a reason to block schooling (Art 28(4))."}},
];
DB.sos={
rights:[
{emoji:"🗣️",t:{en:"1. You must be told why, immediately",tw:"1. Wɔbɛka kyerɛ wo ntɛm",ewe:"1. Woase nukae la",ga:"1. Mi be kɛ ko"},
b:{en:"Ask: 'Why am I arrested?' They must answer in a language you understand.",tw:"Bisa: 'Ɛyɛ dɛn na makyekyerɛ me?' Wɔbɛka kyerɛ wo.",ewe:"Bia: 'Nukae wòde wo la?'",ga:"Bia: 'Kɛ?'"}},
{emoji:"👨‍⚖️",t:{en:"2. You have the right to a lawyer",tw:"2. Wunya mmaranimfo hokwan",ewe:"2. Wò ƒe lawyer ƒe hokwan",ga:"2. Lawyer hokwan"},
b:{en:"Say: 'I want a lawyer of my choice.' They cannot refuse.",tw:"Ka: 'Mepɛ mmaranimfo.'",ewe:"Gblɔ: 'Mefe lawyer.'",ga:"Gbee: 'Kɛ lawyer.'"}},
{emoji:"⏱️",t:{en:"3. Court within 48 hours",tw:"3. Asɛnnibea wɔ ɛnna 48 mu",ewe:"3. Ŋkɔ dom le 48 ŋkeke",ga:"3. Kwe 48"},
b:{en:"You must be brought before a court within 48 hours or released.",tw:"Wɔbɛpisa wo kɔ asɛnnibea wɔ ɛnna 48 mu.",ewe:"Ehiã be woaxɔ ŋkɔ dom le 48 ŋkeke.",ga:"Eehɛ 48 kwe."}},
{emoji:"🕊️",t:{en:"4. You are innocent until proven guilty",tw:"4. Woyɛ pa kosɛ sɛ wɔapɛ wo bɔne",ewe:"4. Wo nye vi alo suku ƒe",ga:"4. Ko be be mi"},
b:{en:"You do not have to prove your innocence.",tw:"Wunni hia sɛ wɔda wo ho pa adi.",ewe:"Wòmehiã be nèda wò ho dzi o.",ga:"Kɛ be mi."}},
{emoji:"🚫",t:{en:"5. No torture, no bribes",tw:"5. Mma abɔ wo, na ɛnyɛ akɔntabuo",ewe:"5. Mehia akpe alo ɖevi",ga:"5. Ko bɛ"},
b:{en:"Nobody may hurt or humiliate you — and you never have to pay a bribe.",tw:"Wunni tumi abɔ wo anaasɛ ɔde wo ayɛ ɔhaw.",ewe:"Ame aɖe melia be yeatseŋ ɖe wo o.",ga:"Ko be be mi."}},
],
contacts:[
{en:"🚓 Ghana Police — 112 (national emergency) or 191",tw:"🚓 Ghana Asoo Nhyehyɛe — 112 alo 191",ewe:"🚓 Polisifo — 112 alo 191",ga:"🚓 Polisifo — 112, 191"},
{en:"⚖️ CHRAJ — visit your regional or district office (free & confidential)",tw:"⚖️ CHRAJ — kɔ wo mpɔtam hɔ adwumakuo",ewe:"⚖️ CHRAJ — yi district ƒe dɔwɔƒe",ga:"⚖️ CHRAJ — district office"},
{en:"🤲 Legal Aid Commission — High Court complex / district office",tw:"🤲 Mmara Mmoa Dwumadibea — asɛnnibea kɛseɛ",ewe:"🤲 Legal Aid Commission — High Court",ga:"🤲 Legal Aid — High Kwe"},
]};
